# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae46ace7d7c724bc0fd1e1626f47f81d74466ffb4fa6088184375efddababb6252b6a32f7591ade6992743c04f401dba64339f99867d91c91b4129f8f3dc564e

test:
  secret_key_base: 5afaea41a99a3b26377d142060abd6d1fb67583b0e05c4668b68278f9266e7872ac825406c73fa0db871f8556581ee5e2e3785ca0484cb030464fcd06fda414e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
